version: '3'

services:
   mariadb:
      image: mariadb
      environment:
         - MYSQL_ROOT_PASSWORD=1234
         - MYSQL_DATABASE=ems
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=123456
      ports:
         - "3306:3306"
      volumes:
         - mariadb-data:/var/lib/mysql
         - ./obo.sql:/docker-entrypoint-initdb.d/init.sql
   web:
      image: obo-spring:latest
      ports:
         - "8085:8080"
      depends_on:
         - mariadb
volumes:
   mariadb-data: