version: '3'

services:
   mariadb:
      image: mariadb
      environment:
         - MYSQL_ROOT_PASSWORD=Password123!
         - MYSQL_DATABASE=obo
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=123456
      ports:
         - "3306:3306"
   web:
      image: obo:latest
      ports:
         - "8085:8080"
      depends_on:
         - mariadb
volumes:
   mariadb-data: